development:
  adapter: postgresql
  encoding: utf8
  database: insta_follow_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: insta_follow_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: insta_follow_production
  pool: 5
  username:
  password:
